services:
  julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - PROXIED=true

  wg-julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - SUBDOMAIN=wg
      - PROXIED=false

  dash-julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - SUBDOMAIN=dash
      - PROXIED=true
