services:
  julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - PROXIED=true

  wg-julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - SUBDOMAIN=wg
      - PROXIED=false

  srv-julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - SUBDOMAIN=srv
      - PROXIED=true

  test-julenoctavio-com:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CF_KEY
      - ZONE=julenoctavio.com
      - SUBDOMAIN=test
      - PROXIED=true