services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - 8080:80
      - 8181:81
      - 443:443
    volumes:
      - $NGINX_PATH/data:/data
      - $NGINX_PATH/letsencrypt:/etc/letsencrypt
      - $NGINX_PATH/_hsts.conf:/app/templates/_hsts.conf:ro

  goaccess:
    image: "xavierh/goaccess-for-nginxproxymanager:latest"
    container_name: goaccess
    restart: always
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Madrid
      - SKIP_ARCHIVED_LOGS=False #optional
      - DEBUG=False #optional
      - BASIC_AUTH=False #optional
      - BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME #optional
      - BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD #optional
      - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited
      - LOG_TYPE=NPM #optional - more information below
      - ENABLE_BROWSERS_LIST=True #optional - more information below
      - CUSTOM_BROWSERS=Kuma:Uptime,TestBrowser:Crawler #optional - comma delimited, more information below
      - HTML_REFRESH=5 #optional - Refresh the HTML report every X seconds. https://goaccess.io/man
      - KEEP_LAST=90 #optional - Keep the last specified number of days in storage. https://goaccess.io/man
      - PROCESSING_THREADS=1 #optional - This parameter sets the number of concurrent processing threads in the program's execution, affecting log data analysis, typically adjusted based on CPU cores. Default is 1. https://goaccess.io/man
    volumes:
      - $NGINX_PATH/data/logs:/opt/log:ro #required - path to your Nginx Proxy Manager logs
      #- /path/to/host/custom:/opt/custom #optional, required if using log_type = CUSTOM #change to the location of your choice
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    environment:
      - DOZZLE_LEVEL=info